### ISSUE TITLE
Upgrade Vendored Terraform to v0.10.6

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-terraform#13]
As identified by @TheLinuxNinja in https://github.com/terraform-providers/terraform-provider-azurerm/issues/351 - in order to support the new `azurerm` backend, the vendor copy of Terraform needs to be updated from `0.10.0` to `0.10.6`

**Comment by apparentlymart** [comment]
Indeed this isn't the first time we've run into this sort of thing. This dependency is pretty troublesome for any backend improvements we make.

In the short term we should indeed just update the vendoring and re-release, but longer term I think it would make sense to fold this provider back into core as an internal provider so that it always upgrades in lockstep with Terraform itself. This is unfortunately easier said than done because we no longer have internal plugin support for providers after the split; we'll need to put in some effort to make that mechanism work again, and in particular make an exception that the `version` argument is not usable with internal plugins.

**Comment by rossedman** [comment]
@tombuildsstuff @apparentlymart any updates on this? just ran into this as well. thanks

**Comment by apparentlymart** [comment]
Hi @rossedman! Sorry for the delay here.

We have some other backend-related changes waiting in `master` for release, so I'd been holding on this until after we get those out, which should be soon.

**Comment by rossedman** [comment]
@apparentlymart cool, thanks a lot. i really appreciate it!

**Comment by apparentlymart** [comment]
Version 1.0.1 of this provider should now have the same backend capabilities as Terraform 0.10.8. Thanks to everyone here for the patience on this.

We're planning to move this provider back to be built into Terraform Core in future since it's very tightly coupled to Terraform's backend behavior, but before we can do that we need to re-introduce some of the local provider behavior that was disabled as part of the core/provider split. Until then, hopefully this updated version of the separated provider will fill the gap.

**Comment by rossedman** [comment]
@apparentlymart thanks so much!

**Comment by trodemaster** [comment]
Any chance we can get some docs/notes on how to update the vendored terraform to the current master branch? I have an issue similar to this one that is fixed post 0.10.8. I'm clear on building plugins but not on the updating the vendor version.
